### ISSUE TITLE
Wont Work

### ISSUE THREAD

**Issue by rcistano** [gigaherz/Ender-Rift#1]
http://paste.ubuntu.com/12065518/

I can send another with just this mod being active.

**Comment by gigaherz** [comment]
I don't even.... how in the heck is 'v 0 0.3566 0.3566' ever considered incorrect?! I'll look into it, but... wow.

**Comment by rcistano** [comment]
No clue. This mod seems interesting. Wouldnt mide being able to use it

**Comment by gigaherz** [comment]
It's a very strange issue because the model loading works both on the development environment, and the testing installation I have on the official launcher.

Looking at the line pointed at by the error log, the issue seems to be the isValidVertexLine() method saying "no" as an answer.

Question: What version of Forge do you have in your launcher? The mod has been tested on 1981, and developed on 1492. I'm currently testing 1492 on the launcher to see if anything changes for me.

**Comment by rcistano** [comment]
Launcher is from the minecraft website, Forge is the current version.

**Comment by rcistano** [comment]
How is the rift made?

**Comment by gigaherz** [comment]
Check the wiki: you create the rift orb and rift core, then build a 3x3x3 multiblock (explained in the wiki) and right-click the core with the orb to complete the structure.

**Comment by rcistano** [comment]
I built it and right clicked on it with the orb but nothing happened

**Comment by gigaherz** [comment]
Did you follow the structure correctly? It has one extra redstone block at the bottom level.

**Comment by gigaherz** [comment]
I'm closing the issue since the crash itself has been solved

**Comment by rcistano** [comment]
Yes, I have built it from the three photos i saw

**Comment by gigaherz** [comment]
And you clicked with the orb item on the core block?

**Comment by rcistano** [comment]
correct

**Comment by gigaherz** [comment]
Well then I have no idea what's wrong -- I have no issues assembling the block, and I have done dozens of them while testing.

**Comment by rcistano** [comment]
I can go back into my test world and re-check

**Comment by rcistano** [comment]
I built the 3x3x3 from Redstone blocks and Quarts Pillar as the pictures show and I have the Rift block in the middle

**Comment by gigaherz** [comment]
Oh! It's not quartz! it's IRON!

**Comment by rcistano** [comment]
from the pictures it shows the Quart Pillars

**Comment by rcistano** [comment]
OK!!! Got it... LMAO... Now that I have the Iron replacing the Quart Pillar then it all work.
