### ISSUE TITLE
[Issue] Proxy not working?

### ISSUE THREAD

**Issue by nlxdodge** [gigaherz/Ender-Rift#10]
I don't know if you finished it yet. but when placing a proxy at the rift and somewhere in the world it won't work.

Empty rift browser with proxy setup:
![emptyriftwithproxy](https://cloud.githubusercontent.com/assets/8994983/13278206/08f7576c-dacf-11e5-885a-9b7be8435e98.png)
Proxy setup localy:
![proxysetup1](https://cloud.githubusercontent.com/assets/8994983/13278204/08f63c2e-dacf-11e5-9916-db6148060426.png)
Normal rift browser content (with at least a lot of energy):
![normalriftinterface](https://cloud.githubusercontent.com/assets/8994983/13278207/08f9cbc8-dacf-11e5-8b53-e0bdadae25c3.png)
Proxy setup on the rifts side:
![proxyconfiguration](https://cloud.githubusercontent.com/assets/8994983/13278205/08f75ed8-dacf-11e5-8a91-b50b8aed4e76.png)

If I put items in the rift when it's connected on the proxy side it will destroy those items.
So I don't know if this is not working yet and DIY, but I couldn't find that or the wiki or somewhere else.

**Comment by gigaherz** [comment]
I guess I did not test the proxy together with the rift itself... I did some extensive testing of the RIFT with chests and other inventories, but I never went back to the rift to check that it still worked... I'll do so later and see what could be wrong

**Comment by gigaherz** [comment]
Oh, I just noticed this is still open. Does the issue still happen with recent builds? I haven't noticed any issue while working on it.
