### ISSUE TITLE
Issue: crashes on startup

### ISSUE THREAD

**Issue by OPlurker1005** [gigaherz/Ender-Rift#11]
Hi I'm a bit new to this crash reporting, but I'm using (Ender-Rift-0.11.2) single player (1.9 forge build 12.16.0.1854)
crash report:
http://pastebin.com/6JXwvuRm

**Comment by gigaherz** [comment]
[v0.11.3](https://github.com/gigaherz/Ender-Rift/releases/tag/v0.11.3) should work.
