### ISSUE TITLE
Crash on Pioneers modpack 1.8.9

### ISSUE THREAD

**Issue by MrTubzy456** [gigaherz/Ender-Rift#12]
Here's the crash report: http://pastebin.com/3XJRBW2Y

The interesting thing is I'm about 5 chunks away from my Ender-rift and it is still crashing me.

**Comment by gigaherz** [comment]
Ah i heard of that issue, but I never encountered it myself -- the TileEntity is still loaded for one tick after the block breaks, so if something happens during that one tick, it can cause issues like that. I'll have to protect all the calls to getBlockState inside my TileEntities.

**Comment by gigaherz** [comment]
I just uploaded v0.10.1 for 1.8.9, which hopefully fixes your crash: https://github.com/gigaherz/Ender-Rift/releases/tag/v0.10.1-1.8.9

Curse upload coming as soon as I press comment. Feel free to comment and/or reopen if it's not fixed.
