### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by tanto259** [gigaherz/Ender-Rift#13]
Running Minecraft 1.9 with Forge 12.6.0.1865
Crash report: [http://pastebin.com/m3by9ApZ](http://pastebin.com/m3by9ApZ)

**Comment by gigaherz** [comment]
I just uploaded v0.12.1 for mc 1.9, which should hopefully fix your issue: https://github.com/gigaherz/Ender-Rift/releases/tag/v0.12.1

Curse upload coming as soon as I press close. Feel free to comment and/or reopen if you still have this issue.
