### ISSUE TITLE
How Many Items can one Ender-Rift theoretically hold?

### ISSUE THREAD

**Issue by starryknight64** [gigaherz/Ender-Rift#14]
Assuming we're trying to store cobblestone, how much can an Ender-Rift hold?

Question was spawned from reddit:
https://www.reddit.com/r/feedthebeast/comments/4hy45k/storage_comparison/

**Comment by gigaherz** [comment]
This is meant for bugs and mod issues, not general discussion. There's the curseforge comments section for that ;P

But regardless, the answer is: There's a hard limit of 10 million RF storage, so assuming the default settings of "1.23 + 0.93*x", where x is the current number of stacks already in the rift, the max is a bit under 11 million STACKS, or almost 70 million cobble (if we were talking about swords, the stack size is 1, so it would only hold the 10.8M. However, that means every insertion at that point would cost 10 million RF, which would be rather expensive to maintain.

**Comment by gigaherz** [comment]
Side-note: if the RF cost was turned off in the settings, then it would be able to hold Integer.MAX_VALUE stacks (2^31-1), which would put the total number of items on over 128 billion.

**Comment by starryknight64** [comment]
Thanks! I'll update the reddit and the spreadsheet. :+1:

**Comment by starryknight64** [comment]
Just making sure I got my math right...
`X=(10,000,000-1.23)/0.93=10,752,687 stacks=688,171,958 cobble`

**Comment by gigaherz** [comment]
Yep.
