### ISSUE TITLE
1.9-0.16.0 crashes dedicated server during game play

### ISSUE THREAD

**Issue by kreezxil** [gigaherz/Ender-Rift#15]
crash report: https://gist.github.com/e308efb917948feaef28c2204654ab2e

**Comment by gigaherz** [comment]
Hmf, this seems to have been a bug for a long time, just one that doesn't happen often. I have a fix for it, but I won't be able to prepare a release in a few hours.

**Comment by kreezxil** [comment]
That's fine

-----Original Message-----

**Comment by gigaherz** [comment]
v0.16.1 should avoid this crash: https://github.com/gigaherz/Ender-Rift/releases
Will be up on curseforge in a minute.
