### ISSUE TITLE
Crash on shift clicking items in

### ISSUE THREAD

**Issue by OPlurker1005** [gigaherz/Ender-Rift#16]
My game crashed when I shift clicked all my items at one time from my inventory into the ender rift. It had nearly 8 million energy, I did not have many things stored inside it yet and I was still charging it when it crash.

crash report: http://pastebin.com/xVP4eR5L

**Comment by gigaherz** [comment]
Gah! Couldn't you have posted this an hour ago? Now I need to release a 0.16.2! Give me a minute ¬¬

(Just kidding, I'm not really angry ;P)

**Comment by gigaherz** [comment]
v0.16.2 is up, and should fix your issue.
