### ISSUE TITLE
Crash on using search

### ISSUE THREAD

**Issue by OPlurker1005** [gigaherz/Ender-Rift#17]
I managed to get all of my items into the ender rift and when I tried to use the search bar on the interface it crashed. I have not tried using the crafting interface but I would guess it will crash as well. I did find out when building the ender rift that braking the crafting interface changes it back into a normal interface, I am not sure if that is a bug or intended as it is not marked as "wip".
crash report: http://pastebin.com/MmNgmsM9

**Comment by gigaherz** [comment]
I released v0.16.2 right before you posted this, which fixed this specific crash.
