### ISSUE TITLE
crash when using search slider

### ISSUE THREAD

**Issue by OPlurker1005** [gigaherz/Ender-Rift#18]
Hey sorry about all the crash reports, but I have another.
I typed lava into search bar and that worked fine for the 3 seconds I have use it, but when I use the slider to move down it crashed. It's happened both times I have loaded into my game since updating.

I used the slider, it crashed and I reloaded. When I logged in the second time a lava tank from NeoTech was floating on the ground in front of the interface which I did not remove from the ender rift when the crash happened.

Not sure if this is important, but I have a large number of lava tanks that do not stack in normal chests and the first spot on the displayed items in the ender rift has it stacked to 2 and the rest of my tanks are singles.

crash report: http://pastebin.com/vxs6kzbV

**Comment by gigaherz** [comment]
No problem. I know about the crash, experienced it myself. I'm trying to figure out exactly WHY it happens, so I can push yet another bugfix.

**Comment by gigaherz** [comment]
Can you verify that 0.16.3 works for you? https://github.com/gigaherz/Ender-Rift/releases

**Comment by OPlurker1005** [comment]
Had to remove 16.2 and drop it in curse didn't update yet, but I can scroll and I'd doesn't crash. Congrats on the fix and thanks for the great mod.

**Comment by gigaherz** [comment]
Thanks :)

**Comment by gigaherz** [comment]
Btw it's up on curseforge now, I didn't upload yet because I was awaiting confirmation.
