### ISSUE TITLE
generator bug?

### ISSUE THREAD

**Issue by wrathyy** [gigaherz/Ender-Rift#20]
whenever I put a bucket of lava into the generator it also consumes the bucket is this a bug or the way it is supposed to work

**Comment by gigaherz** [comment]
Hmm I think I copied the code from the vanilla furnace, but I may not have copied it correctly. Does the bucket remain when you put it on a vanilla furnace? I can't remember and I'm at work.

**Comment by wrathyy** [comment]
yeah the bucket remains if you put it in a vanilla furnace
btw i'm playing in 1.9 version of minecraft if this helps

**Comment by wrathyy** [comment]
also I really hope that you add combatibility with other mods for energy supply like quantumflux

**Comment by gigaherz** [comment]
I'm waiting to see which energy APIs become the more used, since I'd rather avoid using the RF api.

**Comment by wrathyy** [comment]
so about the bucket thing whats going to happen?

**Comment by gigaherz** [comment]
Consider it a bug, unless proven otherwise. I'll take a look at it soon, but I'm a bit busy right now.

**Comment by wrathyy** [comment]
ok thanks m8

**Comment by gigaherz** [comment]
v1.0 includes a fix for this. Have fun (if you use 1.9.4/1.10 -- I may or may not backport that fix later)!
