### ISSUE TITLE
1.8.9 is still crashing on Forge: 11.15.1.1902

### ISSUE THREAD

**Issue by SirBlobman** [gigaherz/Ender-Rift#22]
http://pastebin.com/MiJyHPXL

Every time I right click the Ender Rift Core with an Ender Rift Item it turns my screen Sky Blue and crashes the game

**Comment by gigaherz** [comment]
Hmmm, I suppose I'll have to update forge and recompile. I'm currently building 1.8.9 with forge 1855.

**Comment by SirBlobman** [comment]
I just downgraded Forge to Recommended (I always use Latest) and it seems to work

They must have changed something

**Comment by gigaherz** [comment]
Wait what -- I just checked, I DID use 1902 for the last release!

**Comment by gigaherz** [comment]
See: https://github.com/gigaherz/Ender-Rift/blob/v0.16.3-1.8.9/build.gradle#L22

**Comment by gigaherz** [comment]
I'm confused... "java.lang.NoSuchMethodError: net.minecraft.client.renderer.Tessellator.getBuffer()Lnet/minecraft/client/renderer/WorldRenderer;"

getBuffer?!?! The name was "getWorldRenderer()" in 1.8.9, it wasn't renamed to getBuffer until 1.9.x -- wtf is going on there?

**Comment by SirBlobman** [comment]
Sorry, I just redownloaded the file
Something seems to have gone wrong on my side
