### ISSUE TITLE
Rift Interface - question

### ISSUE THREAD

**Issue by NosajDraw** [gigaherz/Ender-Rift#24]
Does the interface only make available what is in the filter?  Or should anything connected to an interface that has no items in the filter be able to see the whole inventory?

**Comment by gigaherz** [comment]
Only what's in the filter. I may try again in the future, to expose the internal inventory using IItemHandler, but for now, the interface filters are the only way to automate extracting items, and browsing is not supported beyond my own browser block.

**Comment by gigaherz** [comment]
By the way, the Curseforge comments page is a better place for these kinds of questions.
