### ISSUE TITLE
Duping items

### ISSUE THREAD

**Issue by MrAmericanMike** [gigaherz/Ender-Rift#25]
On the 1.5.0 version, when you place a hopper on top and put items on it, all the items get duped.

Well, not much more details to describe ;)

PS: Onyl thing I wish is that it get's JEI Support from inside the storage at some point, in some update :D That would be glorious. And auto refill on the crafting grid if there are items inside the storage.

**Comment by gigaherz** [comment]
By "on it", where do you mean? on the rift itself? on an interface?

**Comment by gigaherz** [comment]
Nevermind, it was easy to reproduce.
