### ISSUE TITLE
[2.0.0] Still some duping and Rift not working

### ISSUE THREAD

**Issue by MrAmericanMike** [gigaherz/Ender-Rift#26]
Ok, so playing with this version (I know its alpha)

http://imgur.com/a/mtYdz

Cant place or take items from the Rift, and got a hopper on top and placed 64 iron blocks, however the interface shows 66, so some duping still happening

**Comment by gigaherz** [comment]
Hmm crap. I forgot about this before doing a quick new year's release.

I just tried placing a hopper on top of the rift, placed 64 items in the hopper, got 128 on the rift. Yep, definitely duplication going on.

**Comment by gigaherz** [comment]
v2.1.2 for 1.11 fixes the issue. I'll try to backport the fixes to 1.10 tomorrow, but I'll also be testing the rest of my mods in 1.11.2 forge, and that takes priority.

**Comment by gigaherz** [comment]
v2.1.3 is out for 1.10.2 and 1.11.x.
