### ISSUE TITLE
generator

### ISSUE THREAD

**Issue by LocoMinerDad** [gigaherz/Ender-Rift#29]
Hi there,
I am trying to use your generators as a power source with RFtools. I have four of them connected to a power cell. The cell is still charging but only two generators are generating power. The other two are cooling down after their internal buffer has reached its max. I have no idea why its maxed since the cell is still charging.

**Comment by gigaherz** [comment]
Could it be that the cell has a RF/t limit and the first two generators are reaching it?

**Comment by LocoMinerDad** [comment]
I didn't think of that. Ok let me expand the situation. I am trying to power a rftools shield. I am using fluxed redstone mod cables to connect your generators to the cell and the shield. All the RF is going to the shield. Your machines still cap and shutdown and the cell isn't charged and the shield is flickering.
