### ISSUE TITLE
Crashes when placing "Ender Sturctur" [1.12]

### ISSUE THREAD

**Issue by Fundryi** [gigaherz/Ender-Rift#31]
The title says it.
https://gist.github.com/Fundryi/06e4fdd87154d996829202c216f599cd

**Comment by gigaherz** [comment]
Ugh... I knew I was forgetting something.... I never tested with WAILA instead of TheOneProbe.

**Comment by Fundryi** [comment]
Haha no problem, I use Hwyla but that doesn't change anything :)

**Comment by gigaherz** [comment]
v2.1.7 is being reviewed on curseforge. Will be available as soon as it's approved.
