### ISSUE TITLE
Request: Is there a 1.12.2 version planned?

### ISSUE THREAD

**Issue by 99Blocks** [gigaherz/Ender-Rift#38]
Hi,

Just as the title suggests I wondered if there will be an "official" release for Minecraft 1.12.2

I am currently working on a new mod-pack and would love to include Ender-Rift in it.
It's providing an excellent storage alternative that fits with the themes of the pack.

I currently have the newest version (Marked as MC 1.12.1 compatible) installed in the pack and it seems to be working ok during tests but to re-distribute the pack I would need a file flagged as "1.12.2 compatible" otherwise Curse will tell me off.

Best regards, with apologies for opening a new issue here,

Robin aka 99Blocks.

**Comment by 99Blocks** [comment]
Thanks :) After a little playing around, I am a bit confused on how things work but that's probably me being a derp. I'll dig around YouTube for a guide!

**Comment by gigaherz** [comment]
I have done some testing and it seems nothing has changed between 1.12.1 and 1.12.2 that could possibly affect the mod, so the last release is now marked as 1.2.2-compatible.
