### ISSUE TITLE
[1.12.2] Powered, but no access

### ISSUE THREAD

**Issue by HyperMan19680** [gigaherz/Ender-Rift#42]
So I powered up an Ender Rift on my game, but when I tried to use the Crafting Browser, it says there's no power, even though I have a Creative Power Cell from Thermal Foundation powering it.

**Comment by gigaherz** [comment]
The Browsers need to be powered separately, using a Driver.

**Comment by HyperMan19680** [comment]
Well that's an inconvenience....

**Comment by HyperMan19680** [comment]
It's a bigger inconvenience than I thought. It'll get in the way of Rift Interfaces if I try to use them in my setup. Unless you know a way to fix this, I don't think I can use this mod anymore.

**Comment by gigaherz** [comment]
If a setup like this with one power source or battery feeding to both the rift structure and a driver block, with a pair of proxy blocks to connect everything, is really that inconvenient.... well then I guess sorry to hear? I'm not going to change the mod design just for that.

![image](https://user-images.githubusercontent.com/685851/82744307-06dc6e80-9d77-11ea-92ab-60328f02eea3.png)

**Comment by HyperMan19680** [comment]
Yeah, discovered the OTHER new block and it works. Sorry about that.

Sent from my iPhone

On May 23, 2020, at 9:29 PM, David Quintana <notifications@github.com<mailto:notifications@github.com>> wrote:


If a setup like this with one power source or battery feeding to both the rift structure and a driver block, with a pair of proxy blocks to connect everything, is really that inconvenient.... well then I guess sorry to hear? I'm not going to change the mod design just for that.

[image]<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F685851%2F82744307-06dc6e80-9d77-11ea-92ab-60328f02eea3.png&data=02%7C01%7C%7Cd14910e79422491be75408d7ff8a4fd6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637258841810289325&sdata=6LSc6jAd%2FUFEAjPvCfSthO7ZMv3sTRNKy0nMJespfjk%3D&reserved=0>
