### ISSUE TITLE
[1.12.2]Ender-Rift Lava Bucket Generator

### ISSUE THREAD

**Issue by newfengye** [gigaherz/Ender-Rift#44]
Generator+Lava Bucket=Bucket ？
no！ The bucket is missing
I really hope this gets fixed, as I love this mod

**Comment by gigaherz** [comment]
Oh oops. I forgot to return the container to the slot after use. I'm trying not to do major changes to 1.12 anymore, but this seems like a small enough and important enough fix to warrant a bugfix release.

**Comment by gigaherz** [comment]
Oh look at this, it's already fixed locally. Oops! Never released a final update for 1.12 after starting the port to 1.14/1.15

**Comment by gigaherz** [comment]
Should be fixed as of 2.1.10 / 2.2.5
