### ISSUE TITLE
I keep gitting this on start up not sure how to fix it

### ISSUE THREAD

**Issue by Dame2711** [gigaherz/Ender-Rift#48]
no such constructor: gigaherz.enderRift.plugins.TheOneProbeProviders.<init>()void/newInvokeSpecial

using version 1.15.2 
I only have ender rift in my mod folder

**Comment by gigaherz** [comment]
This is very strange....
But no matter, I have a fix for a different TOP issue, which I forgot to release for 1.15, so I will do that, and hopefully will fix this too, since it changes that code. :P
