### ISSUE TITLE
Odd behaviour in-game preventing access to current item inventory.

### ISSUE THREAD

**Issue by AngelFluffyOokami** [gigaherz/Ender-Rift#53]
Hi there!
I'm currently experiencing odd behaviour with what is Ender-Rift, as such, I'll try to provide a clear explanation of the problem.

Upon trying to open inventory with an automation browser, it appears as if it were empty, despite yesterday containing items, furthermore, I broke the ender-rift structure and rudimentary generator and replaced them again, using same ender orb and powering it up, it appears to open the rift for a few seconds during which I can access the browser, before it becomes greyed out and the rift collapses as if it were unpowered.

I'm unsure as to if it's an error with my setup, a mod conflict, or an actual bug, help would be appreciated, thanks!

Attached in YouTube video: Problem reproduction.

https://youtu.be/SbRXXU7nhE8

**Comment by gigaherz** [comment]
Uhm... what version of mc? and what version of the mod?
Also, are those bound orbs in your hand?
Also, do you have access to some more powerful power source? The rudimentary generator is only meant as a starting solution until you have better power :P

**Comment by AngelFluffyOokami** [comment]
> Uhm... what version of mc? and what version of the mod?
> Also, are those bound orbs in your hand?
> Also, do you have access to some more powerful power source? The rudimentary generator is only meant as a starting solution until you have better power :P

1.16.5 & 2.2.13

As for the orbs 
![image](https://user-images.githubusercontent.com/59583625/133149886-f7796bae-7f13-4390-8d9a-f7b2dada089f.png)

Might have access? Just not right now, haven't gotten into many other energy mods, kind of hard to do so without a guide book. 

I just /give'd myself a generator, and Ender-Rift seems to be working.

Does the rift use more energy the more loaded with stuff it gets?

**Comment by gigaherz** [comment]
Yes the RF/t grows with the number of occupied slots.

**Comment by AngelFluffyOokami** [comment]
> Yes the RF/t grows with the number of occupied slots.

Oh, thank you for the help!
