### ISSUE TITLE
Crash when the player uses "Pick Block (Middle Click)" on certain items

### ISSUE THREAD

**Issue by Lolothepro** [gigaherz/Ender-Rift#57]
[crash-2024-05-26_14.11.40-client.txt](https://github.com/gigaherz/Ender-Rift/files/15447757/crash-2024-05-26_14.11.40-client.txt)

log file: https://gist.github.com/Lolothepro/fb0be10699732427ba1c5bd16c8b21c6

this is with enderrift:structure_corner

**Comment by gigaherz** [comment]
Oof, I'll look.

**Comment by gigaherz** [comment]
Should be fixed as of 2.9.1, waiting for review at curseforge.
