### ISSUE TITLE
[Bug] Error when breaking rift on server side:

### ISSUE THREAD

**Issue by nlxdodge** [gigaherz/Ender-Rift#7]
**When breaking the Rift my server gifs this error and can't start the world again (I was testing some things so nothing to bad).**

`19:32:25 [ERROR] Encountered an unexpected exception
19:32:25 net.minecraft.util.ReportedException: Ticking block entity
19:32:25 at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707) ~[MinecraftServer.class:?]
19:32:25 at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) ~[ko.class:?]
19:32:25 at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) ~[MinecraftServer.class:?]
19:32:25 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
19:32:25 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
19:32:25 Caused by: java.lang.NullPointerException
19:32:25 at gigaherz.enderRift.blocks.TileEnderRift.getEnergyExtract(TileEnderRift.java:75) ~[TileEnderRift.class:?]
19:32:25 at gigaherz.enderRift.blocks.TileEnderRift.getEffectivePowerUsageToExtract(TileEnderRift.java:94) ~[TileEnderRift.class:?]
19:32:25 at gigaherz.enderRift.blocks.TileEnderRift.extractItems(TileEnderRift.java:217) ~[TileEnderRift.class:?]
19:32:25 at gigaherz.enderRift.blocks.TileInterface.func_73660_a(TileInterface.java:65) ~[TileInterface.class:?]
19:32:25 at net.minecraft.world.World.func_72939_s(World.java:1716) ~[adm.class:?]
19:32:25 at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544) ~[le.class:?]
19:32:25 at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701) ~[MinecraftServer.class:?]
19:32:25 ... 4 more
19:32:25 [ERROR] This crash report has been saved to: C:\Users\Gerben\Documents\1.8.9 Server\.\crash-reports\crash-2016-02-19_19.32.25-server.txt
19:32:25 [INFO] Stopping server
19:32:25 [INFO] Saving players
19:32:25 [INFO] Saving worlds
19:32:25 [INFO] Saving chunks for level 'world'/Overworld
19:32:25 [INFO] Saving chunks for level 'world'/Nether
19:32:25 [INFO] Saving chunks for level 'world'/The End
19:32:26 [INFO] [FML] Unloading dimension 0
19:32:26 [INFO] [FML] Unloading dimension -1
19:32:26 [INFO] [FML] Unloading dimension 1
19:32:26 [INFO] [FML] Applying holder lookups
19:32:26 [INFO] [FML] Holder lookups applied
19:32:26 [INFO] [FML] The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
19:32:26 [GUI] The server has stopped
`
This issue is reproduceable and when you break the rift the whole servers loops the same error it's stuck and your world is corrupt so this is more of an urgent bug?
![schermopname 35](https://cloud.githubusercontent.com/assets/8994983/13185241/55ca1d82-d740-11e5-8cb6-b8acc5d80427.png)

**Comment by gigaherz** [comment]
Hello, I'm working on a workaround for that crash (adding some extra null checks in places I didn't think needed them). I'll release a "bugfix" version in a short while.

**Comment by nlxdodge** [comment]
Good to know; ;) your conecept is really cool, please keep working on it.

**Comment by gigaherz** [comment]
I'd appreciate if you could test the new version before I upload to curse (ended up fixing the new stuff rather than branch an older version): https://github.com/gigaherz/Ender-Rift/releases/tag/v0.9.0

**Comment by nlxdodge** [comment]
I downloaded the 0.9.1 and it's fixed. You can now destroy a rift without actually crashing the server.
