### ISSUE TITLE
[Bug] Generator - RF goes negative.

### ISSUE THREAD

**Issue by nlxdodge** [gigaherz/Ender-Rift#8]
![schermopname 36](https://cloud.githubusercontent.com/assets/8994983/13186042/6d12e4d4-d744-11e5-8eab-fec182a8dc16.png)

In usage with the Energy pipes from: NeoTech.

[EDIT]
When the server restarted the negative number was gone. So I assume it is from neotech,
Testing with another cable now.

[EDIT2]
Ok the generator seems to be stuck with the gui but the output is still going:
![schermopname 37](https://cloud.githubusercontent.com/assets/8994983/13186643/6f9b7588-d747-11e5-982e-4ad95c453d6d.png)
![schermopname 38](https://cloud.githubusercontent.com/assets/8994983/13186644/6fb28e76-d747-11e5-984f-2e1bc8ce9caf.png)
![schermopname 39](https://cloud.githubusercontent.com/assets/8994983/13186645/6fc3ca06-d747-11e5-984b-564c2f166ba1.png)

It also produces this bug with fluxed redstone (cable mod).

**Comment by gigaherz** [comment]
Hmm I have no idea how this would happen... so far as I can tell, my code will never try to send more energy to the pipes than it has itself...

**Comment by gigaherz** [comment]
I see only one single way this could happen: if those pipes return a bigger number than what I pass to the `receiveEnergy` method...

**Comment by nlxdodge** [comment]
Both pipes did not have the official Cofh API installed. I guess that that's the culprit?

**Comment by gigaherz** [comment]
Nah, so far as I know, we all use the unofficial port of the api created by the Progressive Automation guy. If it was not the case, it would crash, not just have subtle errors.

If 0.9.1 still does that... I have no idea what's happening.

**Comment by gigaherz** [comment]
OH! I just realized, there IS a 1.8.9 RF API now! 'll release a 0.9.2 that makes use of it in a moment.

**Comment by gigaherz** [comment]
Here you go: https://github.com/gigaherz/Ender-Rift/releases/tag/v0.9.2

**Comment by nlxdodge** [comment]
Sorry to say, but it's not fixed if you place down an engine and let it run. You can clearly see that it the gui is not calculating right. but the internal buffer is correct.

after 30k the ammount goes minus and that happends 2 times.

**Comment by gigaherz** [comment]
I see! So it wasn't a problem of transmission itself, it's just that the method I used to display the values on the GUI uses only 2 bytes for the data, which limits it to 32767, before it wraps around to -32768.

**Comment by gigaherz** [comment]
Should be working in 0.9.3, enjoy.
