### ISSUE TITLE
[Bug] Depositing items when holding shift with an empy ender-rift crash.

### ISSUE THREAD

**Issue by nlxdodge** [gigaherz/Ender-Rift#9]
[crash-2016-02-22_20.49.06-client.txt](https://github.com/gigaherz/Ender-Rift/files/141317/crash-2016-02-22_20.49.06-client.txt)

See crashlog:
Client crashes when trying to shift click items in the rift.

**Comment by nlxdodge** [comment]
When getting items out of the rift it works fine (With or without energy).
But extracting with or without energy with shift gives a crash. (Works fine when not holding shift).

**Comment by gigaherz** [comment]
Yeah I discovered that just earlier today, while showing the mod to a friend.

**Comment by nlxdodge** [comment]
Off topic: What is the internal buffer size of the rift? It keeps sucking up energy when doing nothing for a long time. Just asking ;)

**Comment by gigaherz** [comment]
10 Million RF, you can see that in WAILA tooltips. ;P

**Comment by gigaherz** [comment]
[v0.10.0](https://github.com/gigaherz/Ender-Rift/releases/tag/v0.10.0) should fix that crash, along with a couple rather bad WTF bugs... I don't know how no one was botherd by them.
